
-- MySQL Script generated by MySQL Workbench
-- Sat May  2 16:58:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oc_restaurant
-- -----------------------------------------------------
CREATE USER 'oc_user'@localhost IDENTIFIED BY 'projet7';
-- -----------------------------------------------------
-- Schema oc_restaurant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oc_restaurant` DEFAULT CHARACTER SET utf8 ;

GRANT ALL PRIVILEGES ON oc_restaurant.* TO 'oc_user'@localhost;

USE `oc_restaurant` ;
