
-- MySQL Script generated by MySQL Workbench
-- Sat May  2 16:58:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- ------ command for command line ------------------
-- mysql -u <user> -p < 01_create_db_user_mysql.sql --


-- -----------------------------------------------------
-- Schema oc_restaurant
-- -----------------------------------------------------
CREATE USER 'oc_user'@localhost IDENTIFIED BY 'projet7';
-- -----------------------------------------------------
-- Schema oc_restaurant
-- -----------------------------------------------------
CREATE DATABASE oc_restaurant CHARACTER SET 'utf8' ;

GRANT ALL PRIVILEGES ON oc_restaurant.* TO 'oc_user'@localhost;

